[package]
name = "lcmspector-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9.7"
mmap = "0.1.1"
mzdata = "0.56.0"
rayon = "1.10.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
